import { requireAppContext } from '@/lib/auth'
import { money, shortDate } from '@/lib/format'
import { createFinanceRecord } from '@/app/actions'

export const dynamic = 'force-dynamic'

export default async function FinancePage() {
  const { supabase, workspace } = await requireAppContext()
  const [{ data: records = [] }, { data: deals = [] }] = await Promise.all([
    supabase.from('finance_records').select('id,total_amount,paid_amount,remaining_amount,payment_status,due_date,invoice_number,deals(deal_title,companies(company_name))').eq('workspace_id', workspace.id).order('due_date'),
    supabase.from('deals').select('id,deal_title,companies(company_name)').eq('workspace_id', workspace.id).order('updated_at', { ascending: false }),
  ])
  const signed = records.reduce((total, item) => total + Number(item.total_amount || 0), 0)
  const collected = records.reduce((total, item) => total + Number(item.paid_amount || 0), 0)
  const pending = records.reduce((total, item) => total + Number(item.remaining_amount || 0), 0)
  return <><header className="page-heading"><div><h1>Finance</h1><p>Every deal connected to what has been invoiced, paid, and still needs chasing.</p></div></header><section className="panel"><div className="metric-stack"><div><span>Total signed value</span><strong>{money(signed)}</strong><small>Across tracked invoices</small></div><div><span>Money collected</span><strong>{money(collected)}</strong><small>Received payments</small></div><div><span>Pending</span><strong>{money(pending)}</strong><small>Needs attention</small></div><div><span>Invoices</span><strong>{records.length}</strong><small>Tracked records</small></div></div></section><section className="panel new-panel" style={{ marginTop: 8 }}><h2>Track a payment</h2><p>Attach an invoice or payment schedule to a signed deal. Remaining balance is calculated by the database.</p><form action={createFinanceRecord}><input type="hidden" name="workspace_id" value={workspace.id}/><div className="form-row"><label>Deal<select required name="deal_id" defaultValue=""><option value="" disabled>Select a deal</option>{deals.map((deal) => <option key={deal.id} value={deal.id}>{deal.companies?.company_name || deal.deal_title} — {deal.deal_title}</option>)}</select></label><label>Invoice number<input name="invoice_number" placeholder="INV-001"/></label></div><div className="form-row"><label>Total amount (ETB)<input required name="total_amount" type="number" min="0" step="0.01" placeholder="0"/></label><label>Paid so far (ETB)<input required name="paid_amount" type="number" min="0" step="0.01" defaultValue="0"/></label></div><div className="form-row"><label>Due date<input name="due_date" type="date"/></label><label>Status<select name="payment_status" defaultValue="pending"><option value="pending">Pending</option><option value="partial">Partial</option><option value="paid">Paid</option><option value="overdue">Overdue</option></select></label></div><button className="primary-button" type="submit">Add payment record</button></form></section><section className="panel" style={{ marginTop: 8 }}><div className="section-label"><h2>Payment tracker</h2><span className="text-action">Live from deal finance</span></div><div className="money-list">{records.length ? records.map((record) => <div className="money-row" key={record.id}><span><strong>{record.deals?.companies?.company_name || record.deals?.deal_title || 'Untitled deal'}</strong><small>{record.invoice_number || 'No invoice number'} · due {shortDate(record.due_date)}</small></span><b>{money(record.remaining_amount)}</b><em>{record.payment_status.replace('_', ' ')}</em></div>) : <div className="empty-board">No finance records yet. Connect payment terms to a deal as soon as it is signed.</div>}</div></section></>
}
