import Icon from '@/src/components/Icon'
import { createCalendarEvent, createContentIdea } from '@/app/actions'
import { requireAppContext } from '@/lib/auth'
import { shortDate } from '@/lib/format'
import ContentPlanner from '@/components/content-planner'

export const dynamic = 'force-dynamic'

export default async function CalendarPage() {
  const { supabase, workspace } = await requireAppContext()
  const [{ data: events = [] }, { data: ideas = [] }] = await Promise.all([
    supabase.from('calendar_events').select('id,title,start_date,end_date,event_type,status,assigned_to').eq('workspace_id', workspace.id).order('start_date').limit(40),
    supabase.from('content_ideas').select('id,title,description,platform,content_type,status,created_at').eq('workspace_id', workspace.id).order('created_at', { ascending: false }).limit(60),
  ])
  const defaultDate = new Date(Date.now() - new Date().getTimezoneOffset() * 60000).toISOString().slice(0, 16)
  return <><header className="page-heading"><div><h1>Content calendar</h1><p>Plan shoots, posts, deadlines, campaigns, and the small details that keep them moving.</p></div></header><section className="panel"><form className="event-form" action={createCalendarEvent}><input type="hidden" name="workspace_id" value={workspace.id}/><label>What’s happening?<input required name="title" placeholder="e.g. Hey Mobile — shoot day 1"/></label><label>When<input required name="start_date" type="datetime-local" defaultValue={defaultDate}/></label><label>Event type<select name="event_type" defaultValue="content_post"><option value="content_post">Content post</option><option value="brand_shoot">Brand shoot</option><option value="client_deadline">Client deadline</option><option value="editing_deadline">Editing deadline</option><option value="meeting">Meeting</option><option value="payment_due">Payment due</option><option value="campaign_launch">Campaign launch</option></select></label><button className="primary-button" type="submit"><Icon name="plus" size={16}/>Add event</button></form></section><ContentPlanner workspaceId={workspace.id} ideas={ideas} events={events}/><div className="dashboard-grid bottom" style={{ marginTop: 8 }}><section className="panel new-panel"><h2>Save an idea</h2><p>Ideas become a real production asset the moment they enter the system.</p><form action={createContentIdea}><input type="hidden" name="workspace_id" value={workspace.id}/><label>Idea title<input required name="title" placeholder="e.g. Make someone laugh in 10 seconds"/></label><div className="form-row"><label>Platform<select name="platform" defaultValue="tiktok"><option value="tiktok">TikTok</option><option value="instagram">Instagram</option><option value="youtube">YouTube</option></select></label><label>Stage<select name="status" defaultValue="idea"><option value="idea">Raw idea</option><option value="scripted">Scripted</option><option value="ready_to_shoot">Ready to shoot</option><option value="ready">Finalized</option></select></label></div><label>Notes<textarea name="description" placeholder="Hook, visual angle, brand context, or first line of the script."/></label><button className="primary-button" type="submit">Save idea</button></form></section><section className="panel"><div className="section-label"><h2>Scheduled work</h2><span className="text-action">{events.length} events</span></div><div className="timeline-list">{events.length ? events.slice(0, 8).map((event) => <div className="timeline-row" key={event.id}><time>{shortDate(event.start_date)}</time><span><strong>{event.title}</strong><small>{event.status}</small></span><span className="timeline-type">{event.event_type.replaceAll('_', ' ')}</span></div>) : <div className="empty-board">Your calendar is open. Add the first post, shoot, deadline, or payment reminder.</div>}</div></section></div></>
}
